language: cpp
dist: xenial
sudo: false

git:
  depth: false
  quiet: true

addons:
  apt:
    packages:
      - cmake
      - libegl1-mesa-dev
      - libglib2.0-dev
      - libxkbcommon-dev
      - libwayland-dev
      - libjson-glib-dev
      - ninja-build
      - python3-pip
      - python3-setuptools
      - python3-wheel

env:
  matrix:
    - BUILD_TYPE=Debug   MESON_BUILD_TYPE=debug   EXPORTABLE_EGL=true
    - BUILD_TYPE=Release MESON_BUILD_TYPE=release EXPORTABLE_EGL=false

cache:
  pip: true
  ccache: true
  directories:
    - $HOME/libwpe
    - $HOME/libwpe-build

install: |-
  : 'Checkout and install libwpe'
  set -e
  if [[ -d ~/libwpe/.git/ ]] ; then
    echo 'Cleaning libwpe clone...'
    pushd ~/libwpe/
    git reset --hard
    git clean -qxdff
    git checkout -f master
  else
    echo 'Cloning libwpe afresh...'
    rm -rf ~/libwpe/
    git clone -q https://github.com/WebPlatformForEmbedded/libwpe ~/libwpe/
    pushd ~/libwpe/
  fi
  mkdir -p ~/libwpe-build/ && cd "$_"
  cmake ~/libwpe/ -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DBUILD_DOCS=OFF -DCMAKE_INSTALL_PREFIX=${HOME}/libwpe-prefix -DCMAKE_INSTALL_LIBDIR=${HOME}/libwpe-prefix/lib
  TERM=dumb cmake --build . --parallel $(nproc) --target install
  popd
  : 'Install Meson'
  python3 -m pip install --upgrade pip meson

script: |-
  : 'Build'
  set -e
  PKG_CONFIG_PATH=${HOME}/libwpe-prefix/lib/pkgconfig \
    meson _build --buildtype=${MESON_BUILD_TYPE} \
    -Dexportable-egl=${EXPORTABLE_EGL}
  ninja -C _build
  DESTDIR="$(pwd)/_prefix" ninja -C _build install
